name: Test
#7.4, '8.0', 8.1, 8.2
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.3]
        wpstarter: [1.*]

    name: PHP:${{ matrix.php }} / WpStarter:${{ matrix.wpstarter }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, iconv, intl, zip, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-wpstarter-${{ matrix.wpstarter }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-wpstarter-${{ matrix.wpstarter }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "wpstarter/framework:${{ matrix.wpstarter }}" --no-interaction --no-update --dev
          composer update --prefer-stable --no-interaction --no-suggest

      - name: Run Unit tests
        run: vendor/bin/phpunit --testsuite Unit
        env:
          RUNNING_IN_CI: true

      - name: Setup dusk/chrome
        run: |
          vendor/bin/dusk-updater update 111 --no-interaction
          chronieum --version

      - name: Run Browser tests
        run: vendor/bin/phpunit --testsuite Browser
        env:
          RUNNING_IN_CI: true
